kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgre-pvc-c
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
