apiVersion: v1
kind: Service
metadata: 
  name: postgre
  labels:
    app: postgre
    visualize: "true"
spec: 
  ports:
    # the port that this service should serve on
    - port: 5432
      name: postgre
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    app: postgre