apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: "5.6"
  template:
    metadata:
      labels:
        app: mysql
        version: "5.6"
        visualize: "true"
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        livenessProbe:
          tcpSocket:
            port: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          # change this
          value: password
        - name: MYSQL_DATABASE
          value: chat
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          # name must match the volume name below
        - name: mysql-persistent-storage
          # mount path within the container
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc